# Book settings
title: How to share software and models via GitHub or other platforms
author: Gerardo Roa Dabike
logo: figures/cadenza_small.png

execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/CadenzaProject/how-share-software-github
  path_to_book: docs
  branch: master

html:
  use_issues_button: true
  use_repository_button: true

launch_buttons:
  notebook_interface: "classic"
  colab_url: "https://colab.research.google.com"
  thebe: true
  binderhub_url: "https://mybinder.org"